# Generated by Django 4.2 on 2023-04-16 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название меню')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название страницы')),
                ('title_in_menu', models.CharField(max_length=300, verbose_name='Название пункта меню')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True, verbose_name='Порядок в уровне меню')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu', to_field='slug', verbose_name='Меню')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='menu.page', verbose_name='Cтраница')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.page', verbose_name='Родитель')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='pages',
            field=models.ManyToManyField(through='menu.MenuPage', to='menu.page'),
        ),
    ]
