# Generated by Django 4.2 on 2024-02-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='menupage',
            options={'ordering': ['order'], 'verbose_name': 'Страница меню', 'verbose_name_plural': 'Страницы меню'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterUniqueTogether(
            name='menupage',
            unique_together={('menu', 'page', 'parent')},
        ),
    ]
